source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden'
gem 'devise'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client'
gem 'mechanize'
gem 'will_paginate', '~> 2.3.16'
gem 'paginate', '~> 1.0.1'
gem 'json', '1.5.0'
