source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client'
gem 'nokogiri', '1.5.0'
gem 'mechanize', '2.7.0' 
gem 'mysql'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate'
gem 'rake', '0.8.7'
gem 'passenger', '4.0.53'
