source_code : BBC
source_name : Balaka BLM Clinic
source_district : Balaka
source_region : Southern Region 
source_address: 127.0.0.1
source_database : opd_database
source_username : admin
source_password : test
source_port : 5984

#not being used sofar
dest_host : 192.168.18.243
dest_port : 5984
dest_username : admin
dest_password : test
dest_database : opd_database
