production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bart2_development
  pool: 5
  username: root
  password: letusout!

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bart2_development
  pool: 5
  username: root
  password: letusout!

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: bart2_development
  pool: 5
  username: root
  password: letusout

